### ISSUE TITLE
word-wrapping has gone horribly wrong

### ISSUE THREAD

**Issue by benbrignell** [benbrignell/principles.design#22]
Example:
![image](https://user-images.githubusercontent.com/362340/33691537-9ec48be4-dae0-11e7-9a9d-ac3bfc6946b1.png)

I've tried a few things, nothing that smart

**Comment by benbrignell** [comment]
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUGH

![image](https://user-images.githubusercontent.com/362340/33692330-acdc2350-dae4-11e7-8460-2b6e1dabfbcd.png)

**Comment by bitmanic** [comment]
So...this opens up a different can of worms, but adding the following style seems to work quite well—at least on my laptop—when the viewport width is in the range of 920px and 1440px wide:

```
@media (min-width: 920px) {
  h2, .h2 {
    font-size: 3.37vw;
  }
}
```

You could add another media query to cap the font size at a certain size once the viewport gets really wide. Going with this approach could mean updating the font sizes of _all_ type on the page, which would be a bit of work. I'm willing to fork and submit a PR if you'd like me to investigate.

Also, hello! Let me introduce myself. The name's Ray, and I am a designer/front-end dev who stumbled across this project via Hacker News. 👋

**Comment by benbrignell** [comment]
Thanks for your suggestion! I will try it out some time this week. I'm also considering making the font-size smaller too - which I've had some feedback about.
