### ISSUE TITLE
Implement tags

### ISSUE THREAD

**Issue by benbrignell** [benbrignell/principles.design#3]
Better tagging and categorising for surfacing mixed resource types

**Comment by benbrignell** [comment]
I can do this but not sure about the best method. Would be great to get some assistance and discuss the best way to do this. Ultimately the /examples page you'd be able to filter the examples by tag. Kind of how http://styleguides.io does it

**Comment by MattGreyDesign** [comment]
If you want a page for each category you would have to do it manually unless you used a plugin, I tend to use https://github.com/avillafiorita/jekyll-datapage_gen which is simple and lightweight.

However, as they are all listed on one page, I suggest using a filtering system like isotope (https://isotope.metafizzy.co/sorting.html) with data attributes much like you are already doing with `list.js`, I think Styleguides does the same thing by the look of it.
