### ISSUE TITLE
Create json file from examples/help wanted for twitter bot

### ISSUE THREAD

**Issue by benbrignell** [benbrignell/principles.design#37]

**Comment by MattGreyDesign** [comment]
If this means a bot to post to Twitter automatically I suggest generating an RSS feed of the posts and using Ifttt to listen and push a message to Twitter when a new post is added/changed. 

As for the JSON, what do you need to generate it for?

**Comment by benbrignell** [comment]
Sorry my self-assigned tasks have no descriptions…

I've already started this. The reason I'm doing it this way instead of via IFTTT/RSS is I'm exporting all posts, links and authors into a json file to generate tweets such as "Check out `10 Principles of Blah` by `Terry Nutkins` `url`" or "`10 Principles of Blah` has no summaries. Can you help? `Contribute url`" … then using https://github.com/galaxykate/tracery and https://github.com/v21/tracerybot 

```
{
	"call": ["Take a look at","Look at this example","Check out"],
	"help": ["Help wanted","Can you help with","Have you thought about contributing?"]
}

```

Then I can alternate the language, instead of having "check out" I can do "take a look at" or "Here are". I can segment the help wanted principles this way to so alternate the message "help wanted with" or "can you help with" or "we'd love it if you could help with".

I've kind of explained it quite crudely but it's quite a cool way to keep things interesting with some human language (and do a lot more than just schedule tweets)

**Comment by MattGreyDesign** [comment]
Sorry, I'm aware these are self assigned tasks, I'm just interested on how you'll go about it as I want to eventually post to Twitter with the project I mentioned before. I like the idea of feeding it multiple human messages 🤔, looks a bit out of my scope though as I'm keeping the overheads as low as possible by not running it on an accessible server, no Cron jobs or dynamicity for me 😢.

**Comment by benbrignell** [comment]
You can run it using cheapbotsdonequick.com - take a look at some of the examples - for free, really easy. I’ve got about 10 bots (like this one https://twitter.com/uivsux). Tracery is super fun to mess around with.

**Comment by MattGreyDesign** [comment]
Just had a look and it looks great, thanks for the link!
