### ISSUE TITLE
Calm Technology example isn't calm

### ISSUE THREAD

**Issue by Vivism** [benbrignell/principles.design#46]
[The example](https://principles.design/examples/principles-of-calm-technology) is ironic when compared to [the original](https://calmtech.com/).

**Comment by benbrignell** [comment]
Can you please expand on what you mean?

**Comment by Vivism** [comment]
The bright yellow blocks and big bold text aren't calming and are, in fact, rather alarming.

**Comment by benbrignell** [comment]
principles.design is a collection of design principles. The website isn't designed to follow all the (currently 135) design principles in the collection. 

The site will improve over time with constructive feedback from the community but at this point this GitHub issue (which was raised to point out irony) isn't ironic and I will be closing it for lack of irony.
