### ISSUE TITLE
Need a little padding for examples

### ISSUE THREAD

**Issue by bharath-bony** [benbrignell/principles.design#48]
![image](https://user-images.githubusercontent.com/17137372/34030524-77329da0-e193-11e7-8912-6e0816b2614e.png)
![image](https://user-images.githubusercontent.com/17137372/34030589-b31f0ae2-e193-11e7-897b-eeb8c74e4e09.png)

**Comment by benbrignell** [comment]
The hover effect on the container was a bit of an afterthought. Obviously this is where the flush-left text looks weird. When I first tried the idea I added padding but the page kind of looked a bit weird and the slight indenting made it hard to scan before hover was applied. I’m thinking of maybe losing the background hover colour and changing the text and divider colour (which is what I started off with). What do you think?

**Comment by benbrignell** [comment]
Fixed, thanks @bharath-bony
