### ISSUE TITLE
yaml multiline issues

### ISSUE THREAD

**Issue by benbrignell** [benbrignell/principles.design#52]
Line breaks are not being processed.

Example:

```
overview: |
  Multi line yaml should support

  line breaks like this.

  I think it's a jekyll issue.
```

Renders:

```
Multi line yaml should support
line breaks like this.
I think it's a jekyll issue.
```

Example of where this isn't working:
Raw: https://raw.githubusercontent.com/benbrignell/principles.design/master/_examples/mercedes-benz.md

Production: https://principles.design/examples/mercedes-benz

**Comment by hankchizljaw** [comment]
Have you tried the [`newline_to_br`](http://liquidmarkup.org/liquid/filters/newline_to_br/) filter?

Example:  `{{ overview | newline_to_br }}`

**Comment by benbrignell** [comment]
Oh my goodness! Are you married!? @hankchizljaw 

Thanks so much

**Comment by hankchizljaw** [comment]
😂 no worries

**Comment by hankchizljaw** [comment]
You might want to look at the `markdownify` filter for this long-term though. It’ll break it up into nice p tags and give you formatting options 👍🏼

**Comment by benbrignell** [comment]
I was actually thinking about this just now. Some of the summaries and overviews contain bullets in their sources so this might be useful. It's just a bit of a headache for contributors  but in most cases is a quick fix when I check out a PR if it breaks stuff.

**Comment by hankchizljaw** [comment]
I wonder if it’s graceful in its fallback for stuff that’s not multiline? I imagine it returns the line in a p tag, so you might be alright.
