### ISSUE TITLE
Home Footer - Unexpected value rendering with the Twitter image on homepage

### ISSUE THREAD

**Issue by alexisbertin** [benbrignell/principles.design#55]
Hello there, not sure if this bug has been reported already but:

![screen shot 2017-12-18 at 10 49 42](https://user-images.githubusercontent.com/26164711/34102527-6a9224d0-e3e1-11e7-8cda-aa6327c48214.png)

**Comment by benbrignell** [comment]
Thanks for spotting, this was a result of `jekyll-seo-tag` getting confused by the config.yml twitter variable. Manually added the address into the footer for now, thanks!
